import { StudentInterface } from "./utils/interfaces/StudentInterfaces";

export let studentData: StudentInterface[] = [
  {
    username: 'Sankalap693',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425986/sankalap_crnawr.jpg',
    password: 'Sankalap@2012',
    lastname: 'Bharti',
    firstname: 'Sankalap',
    fatherName: 'Raju Ram Bharti',
    motherName: 'Mamta Bharti',
    DOB: "2012-01-08",
    gender: "male",
    std: '6',
    aadharNumber: '411791223227',
    fatherContactNumber: '7841985450',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sakshi693',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739809278/WhatsApp_Image_2025-02-13_at_11.11.46_mge81s.jpg',
    password: 'Sakshi@1234',
    lastname: 'Bharti',
    firstname: 'Sakshi',
    fatherName: 'Raju Ram Bharti',
    motherName: 'Mamta Bharti',
    DOB: "",
    gender: "female",
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '7841985450',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sonu867',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425988/sonu_p7oeo7.jpg',
    password: 'Sonu@2010',
    firstname: 'Sonu',
    lastname: 'Kumar',
    fatherName: 'Poddar Kumar',
    motherName: 'Punita Devi',
    DOB: "2010-10-23",
    gender: "male",
    std: '6',
    aadharNumber: '329974266686',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Mariya130',
    profile: '',
    password: 'Mariya@2010',
    firstname: 'Mariya',
    lastname: 'Khan',
    fatherName: 'Mashkur Khan',
    motherName: 'Nazman Khan',
    DOB: "2010-07-27",
    gender: "female",
    std: '8',
    aadharNumber: '472847269684',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Anchal971',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425997/aanchal_jtgwcv.jpg',
    password: 'Anchal@2011',
    lastname: 'Prajapati',
    firstname: 'Anchal',
    fatherName: 'Pyare Prajapati',
    motherName: 'Pushpa Prajapati',
    DOB: "2011-09-08",
    gender: "female",
    std: '8',
    aadharNumber: '466196529675',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Kajal284',
    profile: '',
    password: 'Kajal@2009',
    firstname: 'Kajal',
    lastname: 'Prajapati',
    fatherName: 'Pyare Prajapati',
    motherName: 'Pushpa Prajapati',
    DOB: "2009-04-05",
    gender: "female",
    std: '9',
    aadharNumber: '802926755221',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Rutuja641',
    profile: '',
    password: 'Rutuja@2009',
    firstname: 'Rutuja',
    lastname: 'Khaire',
    fatherName: 'Vikas Khaire',
    motherName: 'Vidya Khaire',
    DOB: "2009-07-28",
    gender: "female",
    std: '9',
    aadharNumber: '606803942736',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Zoya205',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426186/zoya_qn1hjr.jpg',
    password: 'Zoya@2012',
    firstname: 'Zoya',
    lastname: 'Shaikh',
    fatherName: 'Asfaq Shaikh',
    motherName: 'Sabia Shaikh',
    DOB: "2012-09-07",
    gender: "female",
    std: '7',
    aadharNumber: '344797081903',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Swaliha752',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426001/swaliha_as2bvd.jpg',
    password: 'Swaliha@2011',
    firstname: 'Swaliha',
    lastname: 'Mikrani',
    fatherName: 'Hidayatulla Mikrani',
    motherName: 'fatima Mikrani',
    DOB: "2011-09-16",
    gender: "female",
    std: '8',
    aadharNumber: '573687312622',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Nidhi865',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425999/nidhi_nea6mb.jpg',
    password: 'Nidhi@2013',
    lastname: 'Pawar',
    firstname: 'Nidhi',
    fatherName: 'Rohit Pawar',
    motherName: 'Sapna Pawar',
    DOB: "2013-04-01",
    gender: "female",
    std: '6',
    aadharNumber: '418013198390',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Uvesh337',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426001/uvesh_dienu2.jpg',
    password: 'Uvesh@2012',
    firstname: 'Uvesh',
    lastname: 'Choudhary',
    fatherName: 'Usman Choudhary',
    motherName: 'Nasibun Nisha',
    DOB: "2012-01-21",
    gender: "male",
    std: '6',
    aadharNumber: '417450736243',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Prabhat612',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425986/prabhat_hc2vzb.jpg',
    password: 'Prabhat@2013',
    firstname: 'Prabhat',
    lastname: 'Dubey',
    fatherName: 'Arvind Dubey',
    motherName: 'Kajal Dubey',
    DOB: "2013-02-26",
    gender: "male",
    std: '6',
    aadharNumber: '535482375661',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Pratigya781',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425988/pratigya_ajmznr.jpg',
    password: 'Pratigya@2014',
    lastname: 'Dubey',
    firstname: 'Pratigya',
    fatherName: 'Arvind Kumar',
    motherName: 'Kajal Dubey',
    DOB: "2014-02-01",
    gender: "female",
    std: '5',
    aadharNumber: '255518155116',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Ayan941',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426192/ayan_qt4vho.jpg',
    password: 'Ayan@2011',
    firstname: 'Ayan',
    lastname: 'Shaikh',
    fatherName: 'Aslam Shaikh',
    motherName: 'Shabreena',
    DOB: "2011-05-12",
    gender: "male",
    std: '7',
    aadharNumber: '591662033270',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Md. Dilkash705',
    profile: '',
    password: 'Md. Dilkash@2012',
    firstname: 'Md. Dilkash',
    lastname: 'Rja',
    fatherName: 'MD. Aalam Rja',
    motherName: '',
    DOB: "2012-11-24",
    gender: "male",
    std: '6',
    aadharNumber: '569226867134',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Salma799',
    profile: '',
    password: 'Salma@2009',
    lastname: 'Choudhary',
    firstname: 'Salma',
    fatherName: 'Usman Choudhary',
    motherName: 'Nasibun Nisha',
    DOB: "2009-07-15",
    gender: "female",
    std: '9',
    aadharNumber: '949024106598',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Aaliya413',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425987/aaliya_nzpgu9.jpg',
    password: 'Aaliya@2014',
    firstname: 'Aaliya',
    lastname: 'Mikrani',
    fatherName: 'Hidayatulla Mikrani',
    motherName: 'fatima Mikrani',
    DOB: "2014-02-13",
    gender: "female",
    std: '6',
    aadharNumber: '511387370120',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sadhna422',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426185/sadhana_qnwrzi.jpg',
    password: 'Sadhna@2011',
    lastname: 'mahato',
    firstname: 'Sadhna',
    fatherName: 'Sukanta Mahato',
    motherName: 'Ranu Mahato',
    DOB: "2011-01-01",
    gender: "female",
    std: '7',
    aadharNumber: '553877236597',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Siddika159',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425995/Juhi_goluts.jpg',
    password: 'Siddika@2013',
    lastname: 'Juhiakter',
    firstname: 'Siddika',
    fatherName: 'Nazamuddin',
    motherName: 'Mahmudha Khanam',
    DOB: "2013-12-11",
    gender: "female",
    std: '6',
    aadharNumber: '689706188888',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Khushi210',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425994/khushiPaswan_xqcdfh.jpg',
    password: 'Kumari@2011',
    lastname: 'Kumari',
    firstname: 'Khushi',
    fatherName: 'Rambali Paswan',
    motherName: 'Kiran Devi',
    DOB: "2011-01-01",
    gender: "female",
    std: '6',
    aadharNumber: '467738695158',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sanam920',
    profile: '',
    password: 'Sanam@2012',
    firstname: 'Sanam',
    lastname: 'Shaikh',
    fatherName: 'Javeed Shaikh',
    motherName: 'Husna Taj',
    DOB: "2012-09-18",
    gender: "female",
    std: '7',
    aadharNumber: '205716555172',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Ankit999',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425985/Ankit_oqrdzw.jpg',
    password: 'Ankit@2012',
    firstname: 'Ankit',
    lastname: 'Shah',
    fatherName: 'Rajesh Shah',
    motherName: 'Khunti Devi',
    DOB: "2012-10-15",
    gender: "male",
    std: '6',
    aadharNumber: '261522911137',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sahil290',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426002/sahil_ugafyc.jpg',
    password: 'Sahil@2011',
    lastname: 'Muhammad',
    firstname: 'Sahil',
    fatherName: '',
    motherName: '',
    DOB: "2011-01-22",
    gender: "male",
    std: '8',
    aadharNumber: '336725598724',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Khushi741',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425993/khushi_vsbbog.jpg',
    password: 'Khushi@2013',
    lastname: 'Kumari',
    firstname: 'Khushi',
    fatherName: 'Rajesh Shah',
    motherName: 'Khunti Devi',
    DOB: "2013-01-01",
    gender: "female",
    std: '5',
    aadharNumber: '449389161995',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Sneha447',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425986/sneha_b9aadx.jpg',
    password: 'Sneha@2013',
    lastname: 'Gautam',
    firstname: 'Sneha',
    fatherName: 'Prithvi raj Jaiswal',
    motherName: 'Sunita Jaiswal',
    DOB: "2013-01-01",
    gender: "female",
    std: '6',
    aadharNumber: '270353460951',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Aman200',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426001/aman_jhosb5.jpg',
    password: 'Aman@2011',
    lastname: 'Khan',
    firstname: 'Aman',
    fatherName: 'Shahwaz Khan',
    motherName: 'Noor Afza',
    DOB: "2011-06-24",
    gender: "male",
    std: '9',
    aadharNumber: '485290407541',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Aaradhya42',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802456/r3ti6tbowqwsge7abkja.jpg',
    password: 'Aaradhya@2013',
    firstname: 'Aaradhya',
    lastname: 'Singh',
    fatherName: 'Ramashankar Singh',
    motherName: 'Rita Singh',
    DOB: "2013-07-27",
    gender: "female",
    std: '6',
    aadharNumber: '685425367385',
    fatherContactNumber: '8087594452',
    motherContactNumber: '7066801282',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Laxmi683',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426185/laxmi_xomipp.jpg',
    password: 'Laxmi@2011',
    firstname: 'Laxmi',
    lastname: 'Jaiswar',
    fatherName: 'Shyambabu Jaiswar',
    motherName: 'Neelam Jaiswar',
    DOB: "2011-09-12",
    gender: "female",
    std: '7',
    aadharNumber: '555163428287',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Surmila127',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426185/surmila_h4ezgf.jpg',
    password: 'Surmila@2011',
    firstname: 'Surmila',
    lastname: 'Choudhary',
    fatherName: 'Bhanwarlal Choudhary',
    motherName: 'Manju Choudhary',
    DOB: "2011-11-04",
    gender: "female",
    std: '7',
    aadharNumber: '967086856034',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Khushi82',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426185/khushiPal_v8bipz.jpg',
    password: 'Khushi@2012',
    lastname: 'Pal',
    firstname: 'Khushi',
    fatherName: 'Rammurti Pal',
    motherName: 'Bitola Pal',
    DOB: "2012-12-25",
    gender: "female",
    std: '7',
    aadharNumber: '917760491851',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Ayush781',
    profile: '',
    password: 'Ayush@2012',
    firstname: 'Ayush',
    lastname: 'Hate',
    fatherName: 'Anant Hate',
    motherName: 'Ujwala Hate',
    DOB: "2012-06-08",
    gender: "male",
    std: '7',
    aadharNumber: '864562410071',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Afjal105',
    profile: '',
    password: 'Afjal@2012',
    firstname: 'Afjal',
    lastname: 'Ansari',
    fatherName: 'Md. Taj Ansari',
    motherName: 'Shabnam Khatun',
    DOB: "2012-01-29",
    gender: "male",
    std: '6',
    aadharNumber: '305078675614',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Muslim',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Neetu829',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739425995/neetu_kz1n3t.jpg',
    password: 'Neetu@2013',
    lastname: 'Choudhary',
    firstname: 'Neetu',
    fatherName: 'Bhanwarlal Choudhary',
    motherName: 'Manju Choudhary',
    DOB: "2013-11-05",
    gender: "female",
    std: '6',
    aadharNumber: '974634935235',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Guddu4',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426186/guddu_jfwq6x.jpg',
    password: 'Guddu@2011',
    firstname: 'Guddu',
    lastname: 'Kumar',
    fatherName: 'Arjun Kumar',
    motherName: 'Ruhi Devi',
    DOB: "2011-09-01",
    gender: "male",
    std: '7',
    aadharNumber: '504341082262',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    username: 'Suraj339',
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739426192/suraj_vq7wwa.jpg',
    password: 'Suraj@2011',
    firstname: 'Suraj',
    lastname: 'Yadav',
    fatherName: 'Jiyashankar Yadav',
    motherName: 'Usha Yadav',
    DOB: "2011-03-05",
    gender: "male",
    std: '7',
    aadharNumber: '756085322629',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: 'Maharashtra',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804539/xhjwpyt7zzejn4jmg45t.jpg',
    username: 'Yashika77',
    password: 'Yashika@2015',
    lastname: 'Pawar',
    firstname: 'Yashika',
    fatherName: 'Rohit Pawar',
    motherName: 'Sapna Pawar',
    DOB: '2015-01-17',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '7620076977',
    motherContactNumber: '8983041898',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804538/r3uql1p2olc6b3d1qprz.jpg',
    username: 'Sunaina20',
    password: 'Sunaina@2013',
    lastname: 'Chauhan',
    firstname: 'Sunaina',
    fatherName: 'Shivkumar Chauhan',
    motherName: 'Sunita Chauhan',
    DOB: '2013-04-09',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '9156688414',
    motherContactNumber: '8562234625',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Aarya50',
    password: 'Aarya@-ne-',
    lastname: 'Kanojiya',
    firstname: 'Aarya',
    fatherName: 'Santosh Kanojiya',
    motherName: ' Kanojiya',
    DOB: '',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804536/rrnx3lmryvmobb5oicra.jpg',
    username: 'Jasmin82',
    password: 'Jasmin@2014',
    lastname: 'Singh',
    firstname: 'Jasmin',
    fatherName: 'Anup Singh',
    motherName: 'Soniya Singh',
    DOB: '2014-04-09',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '9050290782',
    motherContactNumber: '8950190782',
    email: '',
    address: '',
    religion: 'Hindu',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804537/jjblytayyytdf5fxhbpz.jpg',
    username: 'Laxmi51',
    password: 'Laxmi@2014',
    lastname: 'Singh',
    firstname: 'Laxmi',
    fatherName: 'Navden Singh',
    motherName: 'Madhu Singh',
    DOB: '2014-10-23',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '9769668227',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804541/ooaqddgpqvfko5eunaoa.jpg',
    username: 'Riddhi1',
    password: 'Riddhi@2013',
    lastname: 'Tiwari',
    firstname: 'Riddhi',
    fatherName: 'Vijay Tiwari',
    motherName: 'Kavita Tiwari',
    DOB: '2013-09-10',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '7666491031',
    motherContactNumber: '8081398836',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Nidhi70',
    password: 'Nidhi@-ne-',
    lastname: 'Pandey',
    firstname: 'Nidhi',
    fatherName: 'Viswnath Pandey',
    motherName: ' Pandey',
    DOB: '-ne-No',
    gender: 'female',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Shivansh95',
    password: 'Shivansh@-ne-',
    lastname: 'Yadav',
    firstname: 'Shivansh',
    fatherName: 'Ramadhar Yadav',
    motherName: ' Yadav',
    DOB: '-ne-No',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Aadarsh81',
    password: 'Aadarsh@-ne-',
    lastname: 'Mishra',
    firstname: 'Aadarsh',
    fatherName: 'Brijesh Mishra',
    motherName: ' Mishra',
    DOB: '-ne-No',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Shahid16',
    password: 'Shahid@-ne-',
    lastname: 'Makrani',
    firstname: 'Shahid',
    fatherName: 'Barkad Makrani',
    motherName: ' Makrani',
    DOB: '-ne-No',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Aditya8',
    password: 'Aditya@-ne-',
    lastname: 'Mishra',
    firstname: 'Aditya',
    fatherName: 'Krishna Mishra',
    motherName: ' Mishra',
    DOB: '-ne-No',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804535/uagfavsjrmqqsda3phtg.jpg',
    username: 'Ayansh76',
    password: 'Ayansh@2012',
    lastname: 'Kanojiya',
    firstname: 'Ayansh',
    fatherName: 'Arvind Kanojiya',
    motherName: 'Sushma Kanojiya',
    DOB: '2012-07-22',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '9372961320',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804534/yrl1kpphdgab17brrvq3.jpg',
    username: 'Tilak46',
    password: 'Tilak@2014',
    lastname: 'Dilod',
    firstname: 'Tilak',
    fatherName: 'Rajkapoor Dilod',
    motherName: 'Sunehri Dilod',
    DOB: '2014-08-21',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '9028953378',
    motherContactNumber: '9076109036',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Shanawaz23',
    password: 'Shanawaz@-ne-',
    lastname: 'Shaikh',
    firstname: 'Shanawaz',
    fatherName: 'Nizam Shaikh',
    motherName: ' Shaikh',
    DOB: '-ne-No',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804533/hwh5bto5veopfvlf1jwo.jpg',
    username: 'Rishabh65',
    password: 'Rishabh@2013',
    lastname: 'Kanojiya',
    firstname: 'Rishabh',
    fatherName: 'Sabhjeet Kanojiya',
    motherName: 'Rita Kanojiya',
    DOB: '2013-08-11',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '7985821129',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804532/ak3a0oszjvdwhcufbeco.jpg',
    username: 'Virat39',
    password: 'Virat@2014',
    lastname: '',
    firstname: 'Virat',
    fatherName: ' ',
    motherName: 'Pooja ',
    DOB: '2014-09-29',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '8097650188',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739804531/uvtzrcyx36fo5p1taw7o.jpg',
    username: 'Aditya98',
    password: 'Aditya@2014',
    lastname: 'Jaiswar',
    firstname: 'Aditya',
    fatherName: 'Prithvipal Jaiswar',
    motherName: 'Sunita Jaiswar',
    DOB: '2014-03-17',
    gender: 'male',
    std: '5',
    aadharNumber: '',
    fatherContactNumber: '8104002767',
    motherContactNumber: '8104002767',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802460/yu9beutjwlqkzlpdrsuq.jpg',
    username: 'Sonali76',
    password: 'Sonali@2012',
    lastname: 'Fernandes',
    firstname: 'Sonali',
    fatherName: 'Sandra Fernandes',
    motherName: 'Sandra Fernandes',
    DOB: '2012-06-30',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '9702140373',
    motherContactNumber: '7208282669',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802457/s3f8i08inxwz4nyhgaqw.jpg',
    username: 'Anshika96',
    password: 'Anshika@2012',
    lastname: 'Pal',
    firstname: 'Anshika',
    fatherName: 'Rajesh Pal',
    motherName: 'Manju Pal',
    DOB: '2012-09-07',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '7376741712',
    motherContactNumber: '7860025786',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: '',
    username: 'Mahak42',
    password: 'Mahak@-ne-',
    lastname: 'Tiwari',
    firstname: 'Mahak',
    fatherName: 'Anand Tiwari',
    motherName: ' Tiwari',
    DOB: '-ne-No',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802464/yeyuv1zeqyjxd8qh8jun.jpg',
    username: 'Ishrat38',
    password: 'Ishrat@2013',
    lastname: 'Jahan',
    firstname: 'Ishrat',
    fatherName: 'Mo.Irfan Jahan',
    motherName: 'Shabina Jahan',
    DOB: '2013-01-01',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '8483935899',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802465/qleujwxcnhlwjrespczo.jpg',
    username: 'Ashu84',
    password: 'Ashu@2010',
    lastname: 'Pehalwan',
    firstname: 'Ashu',
    fatherName: 'Kailash Pehalwan',
    motherName: 'Asha Pehalwan',
    DOB: '2010-06-06',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '887198945',
    motherContactNumber: '7768871492',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802912/a2izw0b0z9bhwnmn4wls.jpg',
    username: 'Anju51',
    password: 'Anju@2011',
    lastname: 'Pehalwan',
    firstname: 'Anju',
    fatherName: 'Kailash Pehalwan',
    motherName: 'Asha Pehalwan',
    DOB: '2011-12-25',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '887198945',
    motherContactNumber: '7768871492',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739803213/nxsju1846pqbgtzep32n.jpg',
    username: 'Priti71',
    password: 'Priti@2012',
    lastname: 'Singh',
    firstname: 'Priti',
    fatherName: 'Rajkumar Singh',
    motherName: 'Bibha Singh',
    DOB: '2012-11-21',
    gender: 'female',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '9987200925',
    motherContactNumber: '8097106342',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802911/upak4pnhgbjuh4stjnm5.jpg',
    username: 'Aditya54',
    password: 'Aditya@-ne-',
    lastname: 'Chourasiya',
    firstname: 'Aditya',
    fatherName: 'Vijay Chourasiya',
    motherName: ' Chourasiya',
    DOB: '-ne-No',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '7385577930',
    motherContactNumber: '7066618470',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739803214/pauhf2fyohqiirxouohd.jpg',
    username: 'Fazlu91',
    password: 'Fazlu@2013',
    lastname: 'Shaikh',
    firstname: 'Fazlu',
    fatherName: 'Rahman Shaikh',
    motherName: 'Shaina Shaikh',
    DOB: '2013-06-22',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '8600061927',
    motherContactNumber: '983918197',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: '',
    username: 'Umar93',
    password: 'Umar@-ne-',
    lastname: 'Khan',
    firstname: 'Umar',
    fatherName: ' Khan',
    motherName: ' Khan',
    DOB: '-ne-No',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: '',
    username: 'Md.Aishan51',
    password: 'Md.Aishan@-ne-',
    lastname: 'Khan',
    firstname: 'Md.Aishan',
    fatherName: ' Khan',
    motherName: ' Khan',
    DOB: '-ne-No',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802463/huixtvayiulnky5eykr2.jpg',
    username: 'Raj95',
    password: 'Raj@2013',
    lastname: 'Jaiswar',
    firstname: 'Raj',
    fatherName: 'Shyambabu Jaiswar',
    motherName: 'Neelam Jaiswar',
    DOB: '2013-02-08',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '8793331756',
    motherContactNumber: '9665224185',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739802914/pjupca5i0jgqqnv0o3rp.jpg',
    username: 'Mohit28',
    password: 'Mohit@2010',
    lastname: 'Jaiswar',
    firstname: 'Mohit',
    fatherName: 'Jamindar Jaiswar',
    motherName: 'Mira Jaiswar',
    DOB: '2010-11-26',
    gender: 'male',
    std: '6',
    aadharNumber: '',
    fatherContactNumber: '7447627102',
    motherContactNumber: '8600652968',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805849/cq1chyjajcwud1ouqtqk.jpg',
    username: 'Prem76',
    password: 'Prem@2011',
    lastname: 'Sharma',
    firstname: 'Prem',
    fatherName: ' Sharma',
    motherName: 'Kanchan Sharma',
    DOB: '2011-09-02',
    gender: 'male',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '7773905294',
    motherContactNumber: '7666160635',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805846/lkpkjuiqjfwwcrbdmrbi.jpg',
    username: 'Archana36',
    password: 'Archana@2010',
    lastname: 'Gupta',
    firstname: 'Archana',
    fatherName: ' Gupta',
    motherName: 'Shashi Gupta',
    DOB: '2010-04-28',
    gender: 'female',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '8793932144',
    motherContactNumber: '9152416357',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805847/gudqhznwfwhbjo98ic4h.jpg',
    username: 'Nitesh17',
    password: 'Nitesh@2011',
    lastname: 'Gupta',
    firstname: 'Nitesh',
    fatherName: ' Gupta',
    motherName: 'Sita Gupta',
    DOB: '2011-11-01',
    gender: 'male',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '7738392711',
    motherContactNumber: '7208557548',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805850/g2kmhccqo1fwcqlmgbpx.jpg',
    username: 'Deepika4',
    password: 'Deepika@2012',
    lastname: '',
    firstname: 'Deepika',
    fatherName: ' ',
    motherName: 'Madhu ',
    DOB: '2012-01-28',
    gender: 'female',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '9769668227',
    motherContactNumber: '9730668227',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805845/wgjhawe7ea9ybzaekkmt.jpg',
    username: 'Deepa54',
    password: 'Deepa@2011',
    lastname: 'Yadav',
    firstname: 'Deepa',
    fatherName: ' Yadav',
    motherName: 'Rajkumari Yadav',
    DOB: '2011-08-16',
    gender: 'female',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '9673672184',
    motherContactNumber: '8329488553',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739805844/ljl1u2rzcv8v70zd2in1.jpg',
    username: 'Anita30',
    password: 'Anita@2011',
    lastname: 'Chauhan',
    firstname: 'Anita',
    fatherName: 'Shivkumar Chauhan',
    motherName: 'Sunita Chauhan',
    DOB: '2011-01-09',
    gender: 'female',
    std: '7',
    aadharNumber: '',
    fatherContactNumber: '9156688414',
    motherContactNumber: '8562234625',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806724/xffpec8jat7q32qlzbn1.jpg',
    username: 'Satyam69',
    password: 'Satyam@2011',
    lastname: 'Chaurasiya',
    firstname: 'Satyam',
    fatherName: ' Chaurasiya',
    motherName: 'Babita Chaurasiya',
    DOB: '2011-05-09',
    gender: 'male',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '989050466',
    motherContactNumber: '7080098686',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806732/rm22xb0exdfzihwhuiez.jpg',
    username: 'Priya62',
    password: 'Priya@2012',
    lastname: '',
    firstname: 'Priya',
    fatherName: ' ',
    motherName: 'Mahima ',
    DOB: '2012-06-07',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '9930655631',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806727/loqe74gbulxwn2xul9te.jpg',
    username: 'Aayushi86',
    password: 'Aayushi@2011',
    lastname: '',
    firstname: 'Aayushi',
    fatherName: ' ',
    motherName: 'Bitola ',
    DOB: '2011-04-02',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '7507568746',
    motherContactNumber: '9172770013',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806730/hrgg7khwcknpjwkbs8ph.jpg',
    username: 'Poonam52',
    password: 'Poonam@2011',
    lastname: '',
    firstname: 'Poonam',
    fatherName: ' ',
    motherName: 'Anju ',
    DOB: '2011-01-30',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '9819626966',
    motherContactNumber: '7758986217',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806729/adwdaglxavxrftjfokyu.jpg',
    username: 'Divyanshi42',
    password: 'Divyanshi@2011',
    lastname: '',
    firstname: 'Divyanshi',
    fatherName: ' ',
    motherName: 'Vibha ',
    DOB: '2011-03-20',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '7081717587',
    motherContactNumber: '9511933911',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806733/ue8ahpbirrnj3gnkusah.jpg',
    username: 'Purva60',
    password: 'Purva@2011',
    lastname: 'Pawar',
    firstname: 'Purva',
    fatherName: ' Pawar',
    motherName: 'Sapna Pawar',
    DOB: '2011-06-11',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '7620076977',
    motherContactNumber: '8983041898',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739806726/jfysbuaohrswnhznc7fg.jpg',
    username: 'Shilpa69',
    password: 'Shilpa@2010',
    lastname: '',
    firstname: 'Shilpa',
    fatherName: ' ',
    motherName: 'Usha ',
    DOB: '2010-10-30',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '9545770193',
    motherContactNumber: '9699386762',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: '',
    username: 'Aanchal74',
    password: 'Aanchal@2010',
    lastname: 'Prajapati',
    firstname: 'Aanchal',
    fatherName: ' Prajapati',
    motherName: 'Pushpa Prajapati',
    DOB: '2010-08-08',
    gender: 'female',
    std: '8',
    aadharNumber: '',
    fatherContactNumber: '8400117545',
    motherContactNumber: '',
    email: '',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: "student"
  },
  {
    profile: "",
    username: 'Sumaiya95',
    password: 'Sumaiya@2009',
    lastname: 'Shaikh',
    firstname: 'Sumaiya',
    fatherName: 'Saidul Shaikh',
    motherName: 'Rubina Shaikh',
    DOB: '2009-10-13',
    gender: 'female',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '9932196517',
    motherContactNumber: '9699508678',
    email: "",
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: "",
    username: 'Hajira40',
    password: 'Hajira@2008',
    lastname: 'Choudhary',
    firstname: 'Hajira',
    fatherName: 'Usman Choudhary',
    motherName: 'Nasibun Choudhary',
    DOB: '2008-05-14',
    gender: 'female',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '9922284338',
    motherContactNumber: '7523909814',
    email: "",
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: "",
    username: 'Kajal97',
    password: 'Kajal@2009',
    lastname: 'Bagdhi',
    firstname: 'Kajal',
    fatherName: 'Mithu Bagdhi',
    motherName: 'Jyoti Bagdhi',
    DOB: '2009-03-15',
    gender: 'female',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '8421825396',
    motherContactNumber: '8421825396',
    email: "",
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739857270/bxvlsaaqob0xudcg39rn.jpg',
    username: 'Uzaid64',
    password: 'Uzaid@2011',
    lastname: 'Ansari',
    firstname: 'Uzaid',
    fatherName: 'Afzal Ansari',
    motherName: 'Shabila Ansari',
    DOB: '2011-08-07',
    gender: 'male',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '9012452673',
    motherContactNumber: '7248165138',
    email: 'ansariuzaid786@gmail.com',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739857071/hxqeqkf1rggkjw9v3fcr.jpg',
    username: 'Shivam50',
    password: 'Shivam@2008',
    lastname: 'Dilod',
    firstname: 'Shivam',
    fatherName: 'Rajkapur Dilod',
    motherName: 'Sunheri Dilod',
    DOB: '2008-03-13',
    gender: 'male',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '9028953378',
    motherContactNumber: '9076109036',
    email: 'shivamdilod@gmail.com',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739857072/wra30i94fmmsf2rreiqa.jpg',
    username: 'Hifzul58',
    password: 'Hifzul@2011',
    lastname: 'Shaikh',
    firstname: 'Hifzul',
    fatherName: 'Qumrealam Shaikh',
    motherName: 'Shaina Shaikh',
    DOB: '2011-01-01',
    gender: 'male',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '8600061927',
    motherContactNumber: '9823918197',
    email: 'hifzulshaikh445@gmail.com',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  },
  {
    profile: 'https://res.cloudinary.com/duvoga9f5/image/upload/v1739857070/mxxuz2q6ectb3ynhepcr.jpg',
    username: 'Deepak32',
    password: 'Deepak@2008',
    lastname: 'Prasad',
    firstname: 'Deepak',
    fatherName: 'Suresh Prasad',
    motherName: 'Kiran Prasad',
    DOB: '2008-11-28',
    gender: 'male',
    std: '9',
    aadharNumber: '',
    fatherContactNumber: '8002454219',
    motherContactNumber: '9209374181',
    email: 'deepakprasad9304@gmail.com',
    address: '',
    religion: '',
    birthPlace: '',
    state: '',
    nationality: 'India',
    aadharImage: '',
    birthCertificate: '',
    leavingCertificate: '',
    status: 'student'
  }
]